### ISSUE TITLE
При загрузке object-single фотографии разъезжаются при определённом размере окна браузера

### ISSUE THREAD

**Issue by gennadynikolaev** [yuraloginoff/evans-2#1]

**Comment by yuraloginoff** [comment]
поправил

**Comment by gennadynikolaev** [comment]
Спасибо!

С уважением,
Геннадий Николаев

**Comment by gennadynikolaev** [comment]
Неа, всё равно разъезжаются, если размер окна меньше определенного. Начиная с какого-то азмера и правда всё хорошо, но так и было. Смотрел на evans.surge.sh

**Comment by yuraloginoff** [comment]
Я не заливал туда, проверь еще раз теперь.

**Comment by gennadynikolaev** [comment]
Теперь вроде всё отлично, спасибо!

2015-10-21 15:08 GMT+04:00 Yura Loginov <notifications@github.com>:

> Я не заливал туда, проверь еще раз теперь.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yuraloginoff/evans-2/issues/1#issuecomment-149857229>.
>



-- 
С уважением,
Николаев Геннадий
